name: jejuya
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # [ENV] Load environment variables from .env file at runtime
  flutter_dotenv: ^5.1.0

  # [DI] This is a simple Service Locator for Dart and Flutter projects
  # with some additional goodies highly inspired by Splat
  get_it: ^7.7.0

  # [State Management] Supercharge the state-management in your Dart apps
  # with Transparent Functional Reactive Programming (TFRP).
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # [State Management] A predictable state management library that helps
  provider: ^6.1.2

  # [State - DI - Navigation] GetX is an extra-light and powerful solution for Flutter.
  get:
    git:
      url: https://github.com/timeless-space/getx.git
      ref: v4.6.6-wasm

  # [Local Storage] Hive is a lightweight and blazing fast key-value database written in pure Dart.
  hive_flutter: ^1.1.0

  # [Logger] A simple logging library for Dart and Flutter.
  talker: ^4.3.4
  talker_flutter: ^4.3.4

  # [Animation] A powerful, easy to use and customizable tween library
  flutter_animate: ^4.5.0

  # [Flutter Screen Util] A flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.1

  # [Localization] Easy and Fast internationalizing and localization your Flutter Apps
  easy_localization: ^3.0.7

  # [Collection] A set of high-performance, low-level collection types for Dart
  collection: ^1.18.0

  # [Worker Manager] A Flutter plugin to manage background tasks with a neat API
  worker_manager: ^7.0.2

  # [Path Provider] A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^2.0.0
  path: ^1.9.0

  # [Pull to refresh] Pull to refresh x Pagination wiget
  pull_to_refresh: ^2.0.0

  # [Async] Async package for Dart
  async: ^2.11.0

  # [Flutter SVG] A Flutter package to load SVG images
  flutter_svg: ^2.0.10+1

  # [Mime] Package for working with MIME type definitions and for processing streams of MIME multipart media types
  mime: ^1.0.5

  # [Dio] A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^5.5.0+1

  # [Permission Handler] A plugin for Flutter that provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^11.3.1

  # [Animated Text Kit] Collection of some cool and awesome text animations
  animated_text_kit: ^4.2.2

  # [Uuid] UuidValue is still Experimental and the API for it is in flux, please pay attention to changelogs and versions.
  uuid: ^4.4.2

  # [Json Annotation] Provides Dart Build System builders for handling JSON.
  json_annotation: ^4.9.0

  # [Loading Animation Widget] Prebuilt loading animations for Flutter
  loading_animation_widget: ^1.2.1

  # [Synchronized] A Dart package for single-threaded synchronization primitives.
  synchronized: ^3.1.0+1

  # [Package Info] A Flutter plugin for retrieving information from the application package.
  package_info_plus: ^8.0.2

  # [Glassmorphism] A flutter package to create glassmorphic UI designs easily.
  glassmorphism: ^3.0.0

  # [Clay Containers] These clay containers can become the basis for your own unique neumorphic designs
  clay_containers: ^0.3.4

  # [Lottie] A Flutter package for displaying Lottie animations.
  lottie: ^3.1.2

  # [Google Navigation Bar] A Flutter package for navigation bar.
  google_nav_bar: ^5.0.6
  image_network: ^2.5.6
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.3.2

  # [Google Map Flutter] A Flutter plugin that provides a Google Maps widget.
  google_maps_flutter_web: ^0.5.10
  google_maps_flutter: ^2.9.0

  # [Geolocator] A Flutter plugin for handling location services.
  geolocator: ^13.0.1

  # [Calendar Date Picker] A flutter package for selecting date and time
  calendar_date_picker2: ^1.1.7

  # [Intl] A Dart package for internationalizing Flutter apps.
  intl: ^0.19.0

  # [Number Picker] A flutter package for selecting numbers
  numberpicker: ^2.1.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # [Code Generator] Default build runner tool
  build_runner: ^2.4.11

  # [Code Generator] Code generator for MobX
  mobx_codegen: ^2.6.1

  # [Code Generator] Code generator for Hive
  hive_generator: ^2.0.1

  # [Lint] This package provides lint rules for Dart and Flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0

  # [Flavor] A flutter package that helps you setup multiple flavors easily
  flutter_flavorizr: ^2.2.3
  # [Json Serializable] This package is a code generator that simplifies the process of serializing and deserializing JSON in Dart.
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Regular.ttf
        - asset: assets/fonts/Poppins_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins_Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins_Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins_Medium.ttf
          weight: 500

  assets:
    - .env # Environment variables file
    - assets/translations/ # Translations files
    - assets/images/tab_bar/ # Image tab bar files
    - assets/images/markers/ # Image markers files
